### ISSUE TITLE
Empty route can't be given to ::make

### ISSUE THREAD

**Issue by exafred** [Matt-Becker/Forge#4]
can't go to "root" or home; needs explicit controller reference.

**Comment by exafred** [comment]
/*
		* If stripping the slashes ended up with a completely empty route, then stop. We don't need to use Router::make() for a / URL
		*/
		if(strlen($route) < 0) {
			Log::write("Empty route provided to Router::make()");
			return false;
		} else if(strlen($route) === 0) {
			return $this->BASE;
		}

is fix provided for TT

**Comment by exafred** [comment]
Also check where slashes are stripped in ::make

**Comment by Matt-Becker** [comment]
Resolved in v1.0
